export const LOG_IN = "LOG_IN";
export const LOG_OUT = "LOG_OUT";
export const GET_USERS = "GET_USERS";
export const GET_ROLES = "GET_ROLES";
export const CHANGE_USER_ACTIVE = "CHANGE_USER_ACTIVE";
export const CHANGE_USER_ROLE = "CHANGE_USER_ROLE";
export const GET_NEWS ="GET_NEWS";
export const GET_GAMES ="GET_GAMES";
export const EDIT_GAME ="EDIT_GAME";